---
title: "Learning ggplot2"
author: "Jamie Afflerbach"
date: "10/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r packages}
#install.packages("tidyverse")
## tidyverse is a "packge of packages" and contains many of the packages we will use in the workshop, including ggplot2

#load installed packages using `library()`
library(tidyverse)
```

## Load NP data

```{r load_data}
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

Start with the Califoria (`ca`) dataset

```{r}
head(ca)
View(ca)
```

Plot visitation to all CA National Parks over time

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors))
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name))
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
  theme_bw() +  #this utilized the a different theme (dark on light)
  theme(legend.title = element_blank()) #this removed the legend title
```
Plot visitation to SE region National Parks

```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = state)) +
  theme_minimal() +
  xlab("Year") + #another way to add an x-axis label instead of 'labs()'
  ylab("Visitation") +
  ggtitle("Visitation in SE Region National Parks") +
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, size = 14, hjust = 1, color = "red"))
```

```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors))
```

# Faceting plots

```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  facet_wrap(~ state, scales = "free") +
  theme(axis.text.x = element_text(angle = 90))
```

# geoms

```{r}
ggplot(data = se) +
  geom_jitter(aes(x = park_name, y = visitors, color = park_name), alpha = 0.4, width = 0.1) +
  coord_flip()
```

## `geom_line`

```{r}
ggplot(se) +
  geom_line(aes(x = year, y = visitors, color = park_name)) +
  theme_bw()
```

Multiple geoms on one plot

```{r}
ggplot(data = acadia) +
  geom_point(aes(x = year, y = visitors)) +
  geom_line(aes(x = year, y = visitors)) +
  geom_smooth(aes(x = year, y = visitors))
```


```{r}
ggplot(data = acadia, aes(x = year, y = visitors)) +
  geom_point() +
  geom_line() +
  geom_smooth()
```


```{r}
#install.packages("ggthemes")
library(ggthemes)

ggplot(data = acadia, aes(x = year, y = visitors)) +
  geom_point() +
  geom_line() +
  geom_smooth() +
  theme_gdocs()
```

# Bar Charts

```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")
```

#Save a ggplot

```{r}
myplot <- ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")

myplot

ggsave(filename = "myplot.jpg", myplot, height = 5, width = 5, units = "in")

```



















